# Generated by Django 3.2.10 on 2022-03-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowapp', '0002_alter_user_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amount_info',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
