# Generated by Django 3.2.10 on 2022-03-04 19:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cowapp', '0007_auto_20220305_0103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amount_info',
            old_name='join_dates',
            new_name='join_date',
        ),
        migrations.AddField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
