# Generated by Django 3.2.10 on 2022-03-05 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cowapp', '0009_remove_user_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='updated',
        ),
    ]
