# Generated by Django 4.0.3 on 2022-04-01 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowapp', '0014_remove_order_name_order_join_date_order_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
